-- 코드를 작성해주세요
WITH PARENT_ITEM AS(
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
)

SELECT ii.ITEM_ID, ITEM_NAME
FROM ITEM_INFO ii JOIN PARENT_ITEM pi
ON ii.ITEM_ID = pi.ITEM_ID