-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID 
    FROM ITEM_TREE 
    WHERE PARENT_ITEM_ID IS NOT NULL # IS NOT NULL 처리 안하면 틀림
)
ORDER BY ITEM_ID DESC

# WITH PARENTS AS(
#      SELECT PARENT_ITEM_ID
#      FROM ITEM_TREE
#  )
 
#  SELECT ITEM_ID, ITEM_NAME, RARITY
#  FROM ITEM_INFO I
#  LEFT JOIN PARENTS P
#  ON I.ITEM_ID = P.PARENT_ITEM_ID
#  WHERE PARENT_ITEM_ID IS NULL
#  ORDER BY ITEM_ID DESC
