-- 코드를 작성해주세요
WITH PARENTS AS(
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
LEFT JOIN PARENTS P
ON I.ITEM_ID = P.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC