-- 코드를 작성해주세요
WITH relation AS(
    SELECT a.PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA a JOIN ECOLI_DATA b
    WHERE a.PARENT_ID = b.ID
    GROUP BY a.PARENT_ID
)

SELECT ECOLI_DATA.ID, IFNULL(relation.CHILD_COUNT,0) AS CHILD_COUNT
FROM relation RIGHT JOIN ECOLI_DATA
ON ECOLI_DATA.ID = relation.PARENT_ID