-- 코드를 입력하세요
WITH MAX_FAVORITES AS(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT MF.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM MAX_FAVORITES MF
LEFT JOIN REST_INFO RI
ON MF.FOOD_TYPE = RI.FOOD_TYPE AND MF.MAX_FAVORITES = RI.FAVORITES
ORDER BY FOOD_TYPE DESC