-- 코드를 작성해주세요
-- TOTAL_DISTANCE는 CONCAT()으로 인해 문자열로 변환 → ORDER BY에 사용하면 제대로 정렬이 안된다!

SELECT 
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC;
