# 2022-08부터 2022-10까지 대여 횟수가 5회 이상인 자동차
WITH CAR AS ( 
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

# 아래 Query에 기간 조건 안 붙이면 틀린다!
# 안 붙일 경우, 8~10월 사이에 5건 이상 존재하면서 7월에도 대여건이 존재한다면 결과값으로 7월에 해당하는 대여건까지 나온다.
SELECT MONTH(START_DATE) AS MONTH, CAR.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
    ON CAR.CAR_ID = HIS.CAR_ID
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC

