# 2022-08부터 2022-10까지 대여 횟수가 5회 이상인 자동차
WITH CAR AS ( 
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
    ON CAR.CAR_ID = HIS.CAR_ID
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10 # <- 주의
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC