-- 코드를 작성해주세요
WITH sizePerId AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY AS SIZE, ID
    FROM ECOLI_DATA
), maxSizePerYear AS(
    SELECT MAX(SIZE_OF_COLONY) AS maxSize, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT s.YEAR, m.maxSize - s.SIZE AS YEAR_DEV, s.ID
FROM sizePerId s, maxSizePerYear m
WHERE s.YEAR = m.YEAR
ORDER BY s.YEAR, YEAR_DEV