-- 코드를 작성해주세요
WITH name_info AS(
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER"
)

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO info
WHERE info.FISH_TYPE IN (SELECT FISH_TYPE FROM name_info)