-- 코드를 입력하세요
WITH fh AS (
    SELECT *
    FROM FIRST_HALF
    WHERE TOTAL_ORDER >= 3000
), i AS(
    SELECT *
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = "fruit_based"
)

SELECT fh.FLAVOR
FROM fh JOIN i
WHERE fh.FLAVOR = i.FLAVOR
ORDER BY fh.TOTAL_ORDER DESC