WITH FISH_NAME_LENGTH AS (
    SELECT A.FISH_TYPE, FISH_NAME, LENGTH
    FROM (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) A
    JOIN FISH_NAME_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
)

SELECT ID, FISH_NAME, FNL.LENGTH
FROM FISH_NAME_LENGTH FNL
JOIN FISH_INFO FI
ON FNL.FISH_TYPE = FI.FISH_TYPE AND FNL.LENGTH = FI.LENGTH