-- 코드를 입력하세요
WITH ICECREAM AS(
    SELECT fh.FLAVOR, fh.TOTAL_ORDER, i.INGREDIENT_TYPE
    FROM FIRST_HALF fh JOIN ICECREAM_INFO i
    ON fh.FLAVOR = i.FLAVOR
)

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM
GROUP BY INGREDIENT_TYPE