-- 코드를 입력하세요
WITH board AS(
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', BOARD.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM BOARD, USED_GOODS_FILE
WHERE BOARD.board_id = USED_GOODS_FILE.board_id
ORDER BY FILE_ID DESC